// Code generated by mockery v2.53.3. DO NOT EDIT.

package adapters

import (
	context "context"

	entities "github.com/erainogo/revenue-dashboard/pkg/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockProductSummeryRepository is an autogenerated mock type for the ProductSummeryRepository type
type MockProductSummeryRepository struct {
	mock.Mock
}

type MockProductSummeryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductSummeryRepository) EXPECT() *MockProductSummeryRepository_Expecter {
	return &MockProductSummeryRepository_Expecter{mock: &_m.Mock}
}

// BulkInsert provides a mock function with given fields: ctx, docs
func (_m *MockProductSummeryRepository) BulkInsert(ctx context.Context, docs map[entities.CountrySummaryKey]*entities.CountryLevelRevenue) error {
	ret := _m.Called(ctx, docs)

	if len(ret) == 0 {
		panic("no return value specified for BulkInsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[entities.CountrySummaryKey]*entities.CountryLevelRevenue) error); ok {
		r0 = rf(ctx, docs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductSummeryRepository_BulkInsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkInsert'
type MockProductSummeryRepository_BulkInsert_Call struct {
	*mock.Call
}

// BulkInsert is a helper method to define mock.On call
//   - ctx context.Context
//   - docs map[entities.CountrySummaryKey]*entities.CountryLevelRevenue
func (_e *MockProductSummeryRepository_Expecter) BulkInsert(ctx interface{}, docs interface{}) *MockProductSummeryRepository_BulkInsert_Call {
	return &MockProductSummeryRepository_BulkInsert_Call{Call: _e.mock.On("BulkInsert", ctx, docs)}
}

func (_c *MockProductSummeryRepository_BulkInsert_Call) Run(run func(ctx context.Context, docs map[entities.CountrySummaryKey]*entities.CountryLevelRevenue)) *MockProductSummeryRepository_BulkInsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[entities.CountrySummaryKey]*entities.CountryLevelRevenue))
	})
	return _c
}

func (_c *MockProductSummeryRepository_BulkInsert_Call) Return(_a0 error) *MockProductSummeryRepository_BulkInsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductSummeryRepository_BulkInsert_Call) RunAndReturn(run func(context.Context, map[entities.CountrySummaryKey]*entities.CountryLevelRevenue) error) *MockProductSummeryRepository_BulkInsert_Call {
	_c.Call.Return(run)
	return _c
}

// GetCountryLevelRevenueSortedByTotal provides a mock function with given fields: ctx, offset, imit
func (_m *MockProductSummeryRepository) GetCountryLevelRevenueSortedByTotal(ctx context.Context, offset int, imit int) ([]*entities.CountryLevelRevenue, error) {
	ret := _m.Called(ctx, offset, imit)

	if len(ret) == 0 {
		panic("no return value specified for GetCountryLevelRevenueSortedByTotal")
	}

	var r0 []*entities.CountryLevelRevenue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*entities.CountryLevelRevenue, error)); ok {
		return rf(ctx, offset, imit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*entities.CountryLevelRevenue); ok {
		r0 = rf(ctx, offset, imit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CountryLevelRevenue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, imit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCountryLevelRevenueSortedByTotal'
type MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call struct {
	*mock.Call
}

// GetCountryLevelRevenueSortedByTotal is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - imit int
func (_e *MockProductSummeryRepository_Expecter) GetCountryLevelRevenueSortedByTotal(ctx interface{}, offset interface{}, imit interface{}) *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call {
	return &MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call{Call: _e.mock.On("GetCountryLevelRevenueSortedByTotal", ctx, offset, imit)}
}

func (_c *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call) Run(run func(ctx context.Context, offset int, imit int)) *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call) Return(_a0 []*entities.CountryLevelRevenue, _a1 error) *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call) RunAndReturn(run func(context.Context, int, int) ([]*entities.CountryLevelRevenue, error)) *MockProductSummeryRepository_GetCountryLevelRevenueSortedByTotal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductSummeryRepository creates a new instance of MockProductSummeryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductSummeryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductSummeryRepository {
	mock := &MockProductSummeryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
